// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSummary } from "./AgentSummary";
import type { PolicyView } from "./PolicyView";
import type { TaskSummary } from "./TaskSummary";

/**
 * An agent with everything the detail screen needs.
 */
export type AgentDetail = { 
/**
 * The summary fields.
 */
summary: AgentSummary, 
/**
 * The agent's system instructions.
 */
instructions: string, 
/**
 * Its policy, if one is stored.
 */
policy: PolicyView | null, 
/**
 * Recent tasks, newest first.
 */
recent_tasks: Array<TaskSummary>, 
/**
 * Where relative paths resolve for this agent.
 */
workspace: string, };
