// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An agent, as the list and dashboard show it.
 */
export type AgentSummary = { 
/**
 * Identity.
 */
id: string, 
/**
 * Display name.
 */
name: string, 
/**
 * Provider identifier.
 */
provider: string, 
/**
 * Model identifier.
 */
model: string, 
/**
 * `enabled` or `disabled`.
 */
status: string, 
/**
 * Tools this agent has been given.
 */
tools: Array<string>, 
/**
 * Model turns allowed per run.
 */
max_steps: number, 
/**
 * When it was created.
 */
created_at: string, };
