// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An approval request, carrying everything the card needs to show.
 */
export type ApprovalView = { 
/**
 * Identity.
 */
id: string, 
/**
 * The agent asking.
 */
agent_name: string, 
/**
 * The task it is working on.
 */
task_id: string, 
/**
 * The run.
 */
run_id: string, 
/**
 * The objective, for context.
 */
objective: string, 
/**
 * The tool it wants to invoke.
 */
tool: string, 
/**
 * The validated arguments, as JSON text.
 */
arguments: string, 
/**
 * Assessed risk.
 */
risk: string, 
/**
 * Why the runtime is asking.
 */
reason: string, 
/**
 * Plain-language description of what will happen.
 */
explanation: string, 
/**
 * Resources the action touches.
 */
affected_resources: Array<string>, 
/**
 * Whether the agent has read untrusted data during this run.
 */
tainted: boolean, 
/**
 * Where that data came from.
 */
taint_sources: Array<string>, 
/**
 * Current status.
 */
status: string, 
/**
 * When it was raised.
 */
requested_at: string, 
/**
 * When it was answered.
 */
decided_at: string | null, 
/**
 * The human's note.
 */
note: string | null, };
