// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the interface sends back when a human answers an approval.
 */
export type ApprovalDecisionInput = { 
/**
 * The request being answered.
 */
approval_id: string, 
/**
 * Yes or no.
 */
approved: boolean, 
/**
 * An optional note, recorded with the decision and in the audit log.
 *
 * Carried for an approval as well as a denial: the chain can prove a
 * person allowed a high-risk action, and this is the only place it can
 * say why.
 */
note: string | null, };
