// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the interface sends back when a human answers an approval.
 */
export type ApprovalDecisionInput = { 
/**
 * The request being answered.
 */
approval_id: string, 
/**
 * Yes or no.
 */
approved: boolean, 
/**
 * An optional note, recorded in the audit log.
 */
note: string | null, };
