// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One audit record, with everything the chain stores for it.
 *
 * Unlike [`super::EventView`], nothing is summarised away: the payload is the
 * whole serialised event and both hashes are shown, because this is the view
 * a person opens to check what the log claims.
 */
export type AuditRecordView = { 
/**
 * Identity, shared with the event the record seals.
 */
id: string, 
/**
 * Position in the chain, starting at 1.
 */
sequence: number, 
/**
 * When the event happened.
 */
at: string, 
/**
 * The dotted event name.
 */
kind: string, 
/**
 * The agent involved, if any.
 */
agent_id: string | null, 
/**
 * The task involved, if any.
 */
task_id: string | null, 
/**
 * The run involved, if any.
 */
run_id: string | null, 
/**
 * The serialised event, as JSON text laid out for a person to read.
 */
payload: string, 
/**
 * The hash of the record before this one.
 */
prev_hash: string, 
/**
 * This record's own hash.
 */
hash: string, 
/**
 * Whether this records a refusal, an escalation or a rejection.
 */
security_relevant: boolean, };
