// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether the audit chain still verifies, as of the last check.
 *
 * Checked incrementally: each check verifies only the records written since
 * the one before, linked onto the last record already verified. Settings
 * keeps the full rehash as a deliberate act.
 */
export type AuditHealth = { 
/**
 * How many records the log holds.
 */
events: number, 
/**
 * Whether every record checked so far verifies and links to the one
 * before it.
 */
intact: boolean, 
/**
 * When this answer was produced.
 */
checked_at: string, };
