// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A cadence as a form edits it.
 *
 * Flat rather than tagged, so one form can bind every field and switch
 * between kinds without rebuilding its state. The fields that do not belong
 * to `kind` must be empty; a combination that names two cadences is refused,
 * not resolved by guessing which one was meant.
 */
export type CadenceInput = { 
/**
 * `once`, `every` or `cron`.
 */
kind: string, 
/**
 * Seconds between firings, for `every`.
 */
seconds: number | null, 
/**
 * The expression, for `cron`. Five fields or six.
 */
expression: string | null, 
/**
 * `utc` or `local`, for `cron`. UTC when absent.
 */
clock: string | null, };
