// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What checking a cadence found, before anything is stored.
 */
export type CadencePreview = { 
/**
 * Whether it can be evaluated.
 */
valid: boolean, 
/**
 * Why not, when it cannot.
 */
error: string | null, 
/**
 * The runtime's description of it, when it can.
 */
description: string | null, 
/**
 * The next few occurrences after now, soonest first.
 *
 * Empty for `once`, whose single moment is the schedule's first run and
 * not a property of the cadence.
 */
next_runs: Array<string>, };
