// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A cadence, for display.
 */
export type CadenceView = { 
/**
 * `once`, `every` or `cron`.
 */
kind: string, 
/**
 * Seconds between firings, for `every`.
 */
seconds: number | null, 
/**
 * The expression, for `cron`.
 */
expression: string | null, 
/**
 * `utc` or `local`, for `cron`.
 */
clock: string | null, 
/**
 * The runtime's own description, as the CLI prints it.
 */
description: string, };
