// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How far a policy lets one capability reach.
 */
export type CapabilityReachView = { 
/**
 * The capability, as a policy rule names it: `browser.vision`, not the
 * tool that plans it.
 */
capability: string, 
/**
 * `allowed` for every resource; `scoped`, allowed or asked only for some;
 * `asks`, never allowed outright; `denied`, no rule can allow or ask.
 */
reach: string, };
