// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What is still going on when the window is asked to close.
 *
 * Sent with the close-requested event, so the question the shell asks names
 * what closing will stop rather than asking in general terms.
 */
export type CloseGuard = { 
/**
 * Runs this process is driving.
 */
live_runs: number, 
/**
 * Whether the scheduler is running.
 */
scheduler_running: boolean, 
/**
 * Approval requests in this process still waiting on a person.
 */
pending_approvals: number, };
