// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the interface sends to queue a task.
 */
export type CreateTaskInput = { 
/**
 * The agent that will do it.
 */
agent_id: string, 
/**
 * What to do.
 */
objective: string, 
/**
 * Tasks that must succeed first.
 */
depends_on: Array<string>, 
/**
 * Not before this moment, as RFC 3339.
 */
scheduled_for: string | null, };
