// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CadenceInput } from "./CadenceInput";

/**
 * What the interface sends to create a schedule.
 */
export type CreateScheduleInput = { 
/**
 * The agent that will do the work.
 */
agent_id: string, 
/**
 * Unique name.
 */
name: string, 
/**
 * The objective each firing gets.
 */
objective: string, 
/**
 * How often it fires.
 */
cadence: CadenceInput, 
/**
 * The first occurrence, as RFC 3339. Required for `once`; otherwise the
 * cadence's next occurrence after now.
 */
first_run_at: string | null, };
