// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the interface sends to create an agent.
 */
export type CreateAgentInput = { 
/**
 * Unique name.
 */
name: string, 
/**
 * System instructions.
 */
instructions: string, 
/**
 * Provider identifier.
 */
provider: string, 
/**
 * Model identifier.
 */
model: string, 
/**
 * Base URL override, for OpenAI-compatible endpoints.
 */
base_url: string | null, 
/**
 * Whether this model can be shown images. `null` takes the provider's
 * default, which is off for a local endpoint whose model is unknown.
 */
vision: boolean | null, 
/**
 * Tools to grant.
 */
tools: Array<string>, };
