// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSummary } from "./AgentSummary";
import type { ApprovalView } from "./ApprovalView";
import type { EventView } from "./EventView";
import type { ExecutionView } from "./ExecutionView";
import type { TaskSummary } from "./TaskSummary";

/**
 * The dashboard.
 */
export type DashboardView = { 
/**
 * Every configured agent.
 */
agents: Array<AgentSummary>, 
/**
 * Tasks whose latest run is still going.
 */
running_tasks: Array<TaskSummary>, 
/**
 * Approvals waiting on a human.
 */
pending_approvals: Array<ApprovalView>, 
/**
 * The most recent activity.
 */
recent_events: Array<EventView>, 
/**
 * Recent tool calls that were refused.
 */
recent_refusals: Array<ExecutionView>, 
/**
 * How many events the audit log holds.
 */
audit_events: number, 
/**
 * Whether the audit chain verifies.
 */
audit_intact: boolean, };
