// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSummary } from "./AgentSummary";
import type { ApprovalView } from "./ApprovalView";
import type { ExecutionView } from "./ExecutionView";
import type { TaskSummary } from "./TaskSummary";

/**
 * The dashboard.
 *
 * Polled every few seconds while the window is visible, so it holds only what
 * is cheap to read and changes on that timescale. The audit chain's health is
 * deliberately not here: it has its own command on its own slower schedule.
 */
export type DashboardView = { 
/**
 * Every configured agent.
 */
agents: Array<AgentSummary>, 
/**
 * Tasks whose latest run is still going.
 */
running_tasks: Array<TaskSummary>, 
/**
 * Approvals waiting on a human.
 */
pending_approvals: Array<ApprovalView>, 
/**
 * Recent tool calls that were refused.
 */
recent_refusals: Array<ExecutionView>, 
/**
 * Recent tasks whose latest attempt failed, or that were abandoned.
 *
 * The run's failure text and identity travel on `latest_run`; a task the
 * scheduler abandoned before it ever ran has none.
 */
recent_failures: Array<TaskSummary>, };
