// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One audit event, flattened for the activity feed.
 */
export type EventView = { 
/**
 * Identity.
 */
id: string, 
/**
 * Position in the audit chain, when it came from storage.
 */
sequence: number | null, 
/**
 * When it happened.
 */
at: string, 
/**
 * The dotted event name.
 */
kind: string, 
/**
 * The run it belongs to.
 */
run_id: string | null, 
/**
 * The task it belongs to.
 */
task_id: string | null, 
/**
 * A one-line description.
 */
summary: string, 
/**
 * Whether this records a refusal, an escalation or a rejection.
 */
security_relevant: boolean, };
