// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A tool invocation, with the decision that governed it.
 *
 * The permission effect and taint state are recorded as they were *at the time
 * of the call*, so this stays truthful after the policy changes.
 */
export type ExecutionView = { 
/**
 * Identity.
 */
id: string, 
/**
 * The tool.
 */
tool: string, 
/**
 * The model's call identifier.
 */
call_id: string, 
/**
 * Validated arguments, as JSON text.
 */
arguments: string, 
/**
 * How it ended.
 */
outcome: string, 
/**
 * Whether it actually ran.
 */
executed: boolean, 
/**
 * What the policy decided.
 */
effect: string, 
/**
 * Assessed risk.
 */
risk: string, 
/**
 * Whether the run was tainted at the time.
 */
tainted: boolean, 
/**
 * The approval that gated it, if any.
 */
approval_id: string | null, 
/**
 * How long it took.
 */
duration_ms: number, 
/**
 * Error text, when it failed or was refused.
 */
error: string | null, 
/**
 * When it started.
 */
started_at: string, };
