// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IntegrationAccountView } from "./IntegrationAccountView";

/**
 * An integration the runtime ships, with the accounts bound to it.
 */
export type IntegrationView = { 
/**
 * Identifier, which is also the domain of its tools.
 */
id: string, 
/**
 * Its name as a person writes it.
 */
display_name: string, 
/**
 * The API base URL an account is bound to when none is given.
 */
default_host: string, 
/**
 * Bound accounts, by label.
 */
accounts: Array<IntegrationAccountView>, 
/**
 * The tools it registers, which are what binding an account lets an agent
 * with a matching policy use. Shown before binding so an operator can see
 * what a token would be spent on.
 */
tools: Array<string>, };
