// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What one authenticated read against an account's host found.
 */
export type IntegrationTestView = { 
/**
 * `reachable`, `unauthorised`, `wrong_host` or `unreachable`.
 */
outcome: string, 
/**
 * One line on what was found, never quoting the token.
 */
detail: string, };
