// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An account bound to an integration, as the settings screen lists it.
 *
 * Its token is a network credential stored under the account's API origin and
 * its label, so it is told apart the way a credential is: by where it is
 * bound and what it is called. There is no hint of the value, for the reason
 * [`NetworkCredentialView`](super::NetworkCredentialView) gives, and no source:
 * a network credential is read from the keychain alone, so there is only one
 * place it could have come from.
 */
export type IntegrationAccountView = { 
/**
 * Identity, for unbinding and testing.
 */
id: string, 
/**
 * The operator's name for the account, which a call may use to pick it.
 */
label: string, 
/**
 * The API base URL every request for this account goes to.
 */
host: string, 
/**
 * The origin its token is stored under, which is the host's, or `None`
 * for a row whose host no longer reads as one.
 */
origin: string | null, 
/**
 * Whether the operator let this account reach a private network address,
 * for a GitHub Enterprise server on their own network.
 */
private_network: boolean, 
/**
 * What the operator noted the token can do. A note, not a limit: what an
 * agent may do is the policy's to decide.
 */
scopes: string | null, 
/**
 * Whether the keychain holds a token for the account.
 *
 * `false` is a row with nothing behind it: every call made as the account
 * fails until it is bound again. The screen shows it rather than hiding it,
 * because removing the credential under Network credentials is enough to
 * get here.
 */
credential_present: boolean, 
/**
 * When it was bound.
 */
created_at: string, 
/**
 * When a call last acted as it.
 */
last_used_at: string | null, };
