// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One remembered item.
 */
export type MemoryView = { 
/**
 * Identity.
 */
id: string, 
/**
 * The agent that owns it.
 */
agent_id: string, 
/**
 * `fact`, `decision`, `preference`, `task_history` or `observation`.
 */
kind: string, 
/**
 * The content, exactly as stored.
 */
content: string, 
/**
 * Where it came from, labelled the way taint sources are.
 */
source: string, 
/**
 * Whether that source is outside the trust boundary.
 *
 * A note derived from a webpage is a claim the webpage made, and the
 * person reviewing what an agent will be told must be able to tell it
 * from one they wrote themselves.
 */
source_untrusted: boolean, 
/**
 * Whether memories of this kind are retrieved before planning.
 *
 * Observations and task history are stored but never shown to the model
 * up front; an interface implying otherwise would misdescribe what the
 * model is told.
 */
reaches_the_prompt: boolean, 
/**
 * How much to trust it, 0 to 1.
 */
confidence: number, 
/**
 * The task during which it was recorded.
 */
task_id: string | null, 
/**
 * When it was recorded.
 */
created_at: string, 
/**
 * When it was last revised.
 */
updated_at: string, };
