// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A stored network credential, as the settings screen lists it.
 *
 * An origin and a name, and nothing else: no value, no hint, no length. A
 * provider key shows a redacted hint because a person choosing between keys
 * needs to tell them apart; a credential is told apart by where it is bound,
 * and every character of a secret shown is one fewer to guess.
 */
export type NetworkCredentialView = { 
/**
 * The origin it is bound to, normalised to `scheme://host[:port]`.
 */
origin: string, 
/**
 * The name a request uses to ask for it.
 */
name: string, 
/**
 * The integration account whose token this is, as `GitHub account work`,
 * or `None` for a credential no account uses.
 *
 * One secret is reachable from two sections of the screen. Replacing or
 * removing this credential replaces or removes that account's token, and
 * the screen says so before it does either.
 */
account: string | null, };
