// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PolicyView } from "./PolicyView";

/**
 * The outcome of checking a policy document without installing it.
 */
export type PolicyCheck = { 
/**
 * Whether it compiles.
 */
valid: boolean, 
/**
 * Why not, when it does not.
 */
error: string | null, 
/**
 * What it grants, when it does.
 */
summary: PolicyView | null, };
