// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A policy, summarised so the interface can show what it grants without
 * reimplementing the policy engine.
 */
export type PolicyView = { 
/**
 * The YAML source, exactly as the operator wrote it.
 */
document: string, 
/**
 * Incremented on every save.
 */
version: number, 
/**
 * What happens when no rule matches.
 */
default_effect: string, 
/**
 * Global risk ceiling, if set.
 */
max_risk: string | null, 
/**
 * Whether reading untrusted data raises the approval bar.
 */
taint_enabled: boolean, 
/**
 * The risk level at which that escalation begins.
 */
taint_threshold: string, 
/**
 * One line per rule, in the engine's own words.
 */
rules: Array<string>, };
