// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A model provider and whether it can be used.
 */
export type ProviderView = { 
/**
 * Identifier.
 */
id: string, 
/**
 * Whether a credential is available.
 */
configured: boolean, 
/**
 * A redacted hint, never the key.
 */
hint: string | null, 
/**
 * Which store supplied it.
 */
source: string | null, 
/**
 * Guidance when it is not configured.
 */
note: string, };
