// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the interface sends to record a memory.
 *
 * There is no source field. Whatever arrives is recorded as typed by a
 * person, because that is the only thing this path can attest; see
 * `commands::remember`.
 */
export type RememberInput = { 
/**
 * The agent it is for.
 */
agent_id: string, 
/**
 * One of the kinds [`MemoryView::kind`] lists.
 */
kind: string, 
/**
 * What to remember.
 */
content: string, 
/**
 * How much to trust it, 0 to 1. Full confidence when absent.
 */
confidence: number | null, };
