// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One attempt at a task.
 */
export type RunSummary = { 
/**
 * Identity.
 */
id: string, 
/**
 * 1-based attempt number.
 */
attempt: number, 
/**
 * Where it is in the state machine.
 */
state: string, 
/**
 * Whether it has read untrusted data.
 */
tainted: boolean, 
/**
 * Model turns consumed.
 */
steps: number, 
/**
 * The agent's final report.
 */
result: string | null, 
/**
 * Why it failed, if it did.
 */
failure: string | null, 
/**
 * Input tokens, when the provider reports them.
 *
 * Bound as `number`, not `bigint`: serde emits a JSON number and the IPC
 * layer hands JavaScript a `number`, so a `bigint` binding would describe a
 * wire format that does not exist. None of the counts here — tokens,
 * durations, sequence numbers — comes near 2^53.
 */
input_tokens: number, 
/**
 * Output tokens, when the provider reports them.
 */
output_tokens: number, 
/**
 * When it started.
 */
started_at: string, 
/**
 * When it finished.
 */
completed_at: string | null, };
