// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CadenceView } from "./CadenceView";

/**
 * A schedule, with its agent's name.
 */
export type ScheduleView = { 
/**
 * Identity.
 */
id: string, 
/**
 * Unique, human-chosen name.
 */
name: string, 
/**
 * The agent that does the work.
 */
agent_id: string, 
/**
 * Its name, or `(deleted)`.
 */
agent_name: string, 
/**
 * The objective each firing is given.
 */
objective: string, 
/**
 * How often it fires.
 */
cadence: CadenceView, 
/**
 * `active`, `paused` or `finished`.
 */
status: string, 
/**
 * When it next fires; absent when it never will again.
 */
next_run_at: string | null, 
/**
 * When it last fired.
 */
last_run_at: string | null, 
/**
 * The task the last firing created.
 */
last_task_id: string | null, 
/**
 * When it was created.
 */
created_at: string, };
