// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether the scheduler is running, and the work it would find if it were.
 *
 * The counts are read from the database on every request, not from the
 * scheduler, so they are true whether it is running or not: a stopped
 * scheduler with overdue schedules is exactly the state this view exists to
 * make visible.
 */
export type SchedulerView = { 
/**
 * Whether a scheduler is ticking in this process.
 */
running: boolean, 
/**
 * Seconds between ticks, running or not: what a start would use.
 */
tick_seconds: number, 
/**
 * How many runs it may have in flight at once.
 */
max_concurrent_runs: number, 
/**
 * When the running scheduler started.
 */
started_at: string | null, 
/**
 * Why the scheduler stopped without being asked to, if it did.
 *
 * A scheduler that could not take its lease, or lost its database, ends on
 * its own; without this the switch would simply read "off" again with no
 * account of why.
 */
error: string | null, 
/**
 * Schedules that are active.
 */
active_schedules: number, 
/**
 * The soonest moment an active schedule fires.
 */
next_fire_at: string | null, 
/**
 * Active schedules whose moment has already passed.
 */
overdue: number, 
/**
 * Queued tasks a tick would start now.
 */
runnable_tasks: number, 
/**
 * Queued tasks that can never start, because something they wait for
 * failed or was cancelled.
 */
unreachable_tasks: number, };
