// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderView } from "./ProviderView";
import type { ToolView } from "./ToolView";

/**
 * The settings screen.
 */
export type SettingsView = { 
/**
 * Where AgentOS keeps its state.
 */
data_dir: string, 
/**
 * Agent workspaces.
 */
workspace: string, 
/**
 * The database file.
 */
database: string, 
/**
 * Whether the OS keychain is usable here.
 */
keychain_available: boolean, 
/**
 * Why not, when it is not.
 */
keychain_reason: string | null, 
/**
 * Providers and their credential status.
 */
providers: Array<ProviderView>, 
/**
 * The browser executable that will be driven, if one was found.
 */
browser_path: string | null, 
/**
 * Guidance when no browser is installed.
 */
browser_hint: string | null, 
/**
 * Every tool an agent can be granted.
 */
tools: Array<ToolView>, };
