// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The result of starting a task.
 */
export type StartedTask = { 
/**
 * The task that was created.
 */
task_id: string, 
/**
 * The run that is executing it.
 */
run_id: string, };
