// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry in a run's trace.
 */
export type StepView = { 
/**
 * Position within the run.
 */
ordinal: number, 
/**
 * What kind of thing happened.
 */
kind: string, 
/**
 * The state the run was in.
 */
state: string, 
/**
 * Human-readable summary.
 */
summary: string, 
/**
 * The tool execution this refers to, if any.
 */
tool_execution_id: string | null, 
/**
 * When it happened.
 */
at: string, };
