// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One task in the dependency graph.
 *
 * Its own type rather than more fields on [`super::TaskSummary`]: the graph
 * is a different question ("what is this waiting for?") from the task list's
 * ("how did its latest attempt go?"), and answering both everywhere would make
 * every list pay for the graph.
 */
export type TaskNodeView = { 
/**
 * Identity.
 */
id: string, 
/**
 * What was asked for.
 */
objective: string, 
/**
 * Aggregate status.
 */
status: string, 
/**
 * The agent responsible.
 */
agent_id: string, 
/**
 * Its name, or `(deleted)`.
 */
agent_name: string, 
/**
 * Not before this moment, if the task was queued for one.
 */
scheduled_for: string | null, 
/**
 * The schedule whose firing created it, if any.
 */
schedule_id: string | null, 
/**
 * When it was created.
 */
created_at: string, 
/**
 * The tasks it waits for.
 */
blocked_by: Array<string>, 
/**
 * The tasks that wait for it.
 */
blocks: Array<string>, 
/**
 * Whether a scheduler tick would start it now.
 */
runnable: boolean, 
/**
 * Whether it can never start, because something it waits for failed or
 * was cancelled.
 */
unreachable: boolean, 
/**
 * The dependency that failed or was cancelled, when it is unreachable.
 *
 * The same culprit the scheduler names when it abandons the task, so the
 * two describe one dead branch the same way. A task that waits forever
 * must never look like one nobody has got to yet.
 */
blocked_by_failure: string | null, };
