// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunSummary } from "./RunSummary";

/**
 * A task and the state of its latest attempt.
 */
export type TaskSummary = { 
/**
 * Identity.
 */
id: string, 
/**
 * What was asked for.
 */
objective: string, 
/**
 * Aggregate status.
 */
status: string, 
/**
 * The agent responsible.
 */
agent_name: string, 
/**
 * Its identity, for navigation.
 */
agent_id: string, 
/**
 * When created.
 */
created_at: string, 
/**
 * When the latest run finished.
 */
completed_at: string | null, 
/**
 * The latest run, if the task has ever run.
 */
latest_run: RunSummary | null, };
