// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A tool, as the catalogue and the agent editor show it.
 */
export type ToolView = { 
/**
 * Fully-qualified name.
 */
name: string, 
/**
 * Domain half of the name.
 */
domain: string, 
/**
 * What it does, in the words the model sees.
 */
description: string, 
/**
 * Baseline risk.
 */
risk: string, 
/**
 * Whether its output can be attacker-controlled.
 *
 * The single most useful thing to know when deciding what to grant, so it
 * is surfaced rather than buried in the description.
 */
returns_untrusted_data: boolean, };
