// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityReachView } from "./CapabilityReachView";

/**
 * One granted tool, and how far its policy reaches for each capability the
 * tool declares.
 *
 * Granting a tool and permitting what it does are separate acts, and an agent
 * editor that shows only the first invites the belief that a ticked box is a
 * permission. This is the second, computed by the permission engine from the
 * compiled policy, honouring each rule's effect, rather than by matching rule
 * text in the interface.
 */
export type ToolGrantView = { 
/**
 * Fully-qualified tool name.
 */
tool: string, 
/**
 * Whether this installation has the tool. A tool granted by name and
 * missing from the registry can never be called, whatever the policy
 * says, and has no capabilities to report.
 */
registered: boolean, 
/**
 * The least of its capabilities' reaches: a call needs every capability
 * it plans, so a tool reaches no further than its weakest one.
 */
reach: string, 
/**
 * One entry per capability the tool's manifest declares.
 */
capabilities: Array<CapabilityReachView>, };
