// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One tool's calls over a window, with the catalogue facts that frame them.
 *
 * The buckets are not exclusive: `under_taint` and `approvals` cut across the
 * outcomes. `executed`, `denied`, `approval_denied` and `failed` are each a
 * count of calls that ended that way.
 */
export type ToolUsageView = { 
/**
 * The tool.
 */
tool: string, 
/**
 * Every call in the window, however it ended.
 */
calls: number, 
/**
 * Calls that ran.
 */
executed: number, 
/**
 * Calls the policy refused.
 */
denied: number, 
/**
 * Calls refused at the approval step: by a person, or by the run's
 * approval budget without anyone being asked.
 */
approval_denied: number, 
/**
 * Calls that ran and failed.
 */
failed: number, 
/**
 * Calls made after the run had read untrusted data.
 */
under_taint: number, 
/**
 * Calls that waited on a person.
 */
approvals: number, 
/**
 * Time spent in the tool across every call.
 */
total_duration_ms: number, 
/**
 * The most recent call in the window.
 */
last_used_at: string | null, 
/**
 * Baseline risk, when the tool is still in the catalogue.
 *
 * `None` for a tool that has calls on record but is no longer offered.
 */
risk: string | null, 
/**
 * Whether the catalogue says the tool reads the world outside the runtime.
 */
returns_untrusted_data: boolean, };
