// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalView } from "./ApprovalView";
import type { ExecutionView } from "./ExecutionView";
import type { RunSummary } from "./RunSummary";
import type { StepView } from "./StepView";

/**
 * Everything recorded about one run.
 */
export type TraceView = { 
/**
 * The run.
 */
run: RunSummary, 
/**
 * The task's identity.
 */
task_id: string, 
/**
 * The agent that performed it.
 */
agent_name: string, 
/**
 * What it was asked to do.
 */
objective: string, 
/**
 * The ordered trace.
 */
steps: Array<StepView>, 
/**
 * Tool invocations and their decisions.
 */
executions: Array<ExecutionView>, 
/**
 * Approvals raised during the run.
 */
approvals: Array<ApprovalView>, };
